import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import { Toaster } from "@/components/ui/toaster" 
import { FooterLayout } from "@/components/home/footerLayout";
import { Sidbar } from "@/components/sidbar/sidbar";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-[700px] `}>
       <SessionProvider>
      <NextSSRPlugin
       routerConfig={extractRouterConfig(ourFileRouter)}
        /> 
        <div>
          <Sidbar />
        </div>
      <main className=" pt-20">{children}</main>
        <Toaster />
        <FooterLayout/>
        </SessionProvider>
        </body>
        
    </html>
  );
}
