import { Button } from "@/components/ui/button";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { MdCategory } from "react-icons/md";
import { TbCategoryPlus } from "react-icons/tb";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <div className={`${inter.className} container px-4 `}>
        <div className=" flex justify-between flex-wrap">
          <div className="md:flex justify-between">
            <div className="bg-emerald-400 px-4 min-h-72 md:relative text-white">
              <div className="sm:flex">
                <Button variant="ghost" size="lg" className="text-lg underline">
                  <TbCategoryPlus className="mx-2" />
                  <Link href="/dashboard">Créer un article</Link>
                </Button>
              </div>
              <div>
                <Button variant="ghost" className="text-lg underline">
                  <MdCategory className="mx-2" />
                  <Link href="/dashboard/analitics">Alalitics</Link>
                </Button>
              </div>
            </div>
          </div>
           <div className=" relative mb-4">
          {children}
        </div>
        </div>
       
      </div>
    
  );
}
